/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BudgetRange = { 'Above80L' : null } |
  { 'ThirtyTo50L' : null } |
  { 'Under30L' : null } |
  { 'FiftyTo80L' : null };
export interface Inquiry {
  'id' : bigint,
  'name' : string,
  'propertyId' : [] | [bigint],
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type LifestyleTag = { 'GreatView' : null } |
  { 'LuxuryAmenities' : null } |
  { 'InvestmentReady' : null } |
  { 'NearSchools' : null } |
  { 'ReadyToMove' : null } |
  { 'FamilyFriendly' : null };
export interface Property {
  'id' : bigint,
  'title' : string,
  'propertyType' : PropertyType,
  'imageUrls' : Array<string>,
  'bedrooms' : bigint,
  'tags' : Array<LifestyleTag>,
  'description' : string,
  'postedDaysAgo' : bigint,
  'furnished' : string,
  'isFeatured' : boolean,
  'areaSqft' : bigint,
  'isNew' : boolean,
  'bathrooms' : bigint,
  'price' : bigint,
  'locality' : string,
  'budgetRange' : BudgetRange,
  'location' : string,
  'priceLabel' : string,
}
export interface PropertyFilter {
  'propertyType' : [] | [PropertyType],
  'tags' : Array<LifestyleTag>,
  'searchQuery' : [] | [string],
  'locality' : [] | [string],
  'budgetRange' : [] | [BudgetRange],
}
export type PropertyType = { 'Commercial' : null } |
  { 'Plot' : null } |
  { 'Villa' : null } |
  { 'Penthouse' : null } |
  { 'Apartment' : null };
export interface _SERVICE {
  'getFeatured' : ActorMethod<[], Array<Property>>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getProperties' : ActorMethod<[PropertyFilter], Array<Property>>,
  'getProperty' : ActorMethod<[bigint], [] | [Property]>,
  'getRecommended' : ActorMethod<[bigint], Array<Property>>,
  'submitInquiry' : ActorMethod<
    [string, string, string, [] | [bigint]],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];