/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PropertyType = IDL.Variant({
  'Commercial' : IDL.Null,
  'Plot' : IDL.Null,
  'Villa' : IDL.Null,
  'Penthouse' : IDL.Null,
  'Apartment' : IDL.Null,
});
export const LifestyleTag = IDL.Variant({
  'GreatView' : IDL.Null,
  'LuxuryAmenities' : IDL.Null,
  'InvestmentReady' : IDL.Null,
  'NearSchools' : IDL.Null,
  'ReadyToMove' : IDL.Null,
  'FamilyFriendly' : IDL.Null,
});
export const BudgetRange = IDL.Variant({
  'Above80L' : IDL.Null,
  'ThirtyTo50L' : IDL.Null,
  'Under30L' : IDL.Null,
  'FiftyTo80L' : IDL.Null,
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'propertyType' : PropertyType,
  'imageUrls' : IDL.Vec(IDL.Text),
  'bedrooms' : IDL.Nat,
  'tags' : IDL.Vec(LifestyleTag),
  'description' : IDL.Text,
  'postedDaysAgo' : IDL.Nat,
  'furnished' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'areaSqft' : IDL.Nat,
  'isNew' : IDL.Bool,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'locality' : IDL.Text,
  'budgetRange' : BudgetRange,
  'location' : IDL.Text,
  'priceLabel' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'propertyId' : IDL.Opt(IDL.Nat),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const PropertyFilter = IDL.Record({
  'propertyType' : IDL.Opt(PropertyType),
  'tags' : IDL.Vec(LifestyleTag),
  'searchQuery' : IDL.Opt(IDL.Text),
  'locality' : IDL.Opt(IDL.Text),
  'budgetRange' : IDL.Opt(BudgetRange),
});

export const idlService = IDL.Service({
  'getFeatured' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getProperties' : IDL.Func([PropertyFilter], [IDL.Vec(Property)], ['query']),
  'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
  'getRecommended' : IDL.Func([IDL.Nat], [IDL.Vec(Property)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PropertyType = IDL.Variant({
    'Commercial' : IDL.Null,
    'Plot' : IDL.Null,
    'Villa' : IDL.Null,
    'Penthouse' : IDL.Null,
    'Apartment' : IDL.Null,
  });
  const LifestyleTag = IDL.Variant({
    'GreatView' : IDL.Null,
    'LuxuryAmenities' : IDL.Null,
    'InvestmentReady' : IDL.Null,
    'NearSchools' : IDL.Null,
    'ReadyToMove' : IDL.Null,
    'FamilyFriendly' : IDL.Null,
  });
  const BudgetRange = IDL.Variant({
    'Above80L' : IDL.Null,
    'ThirtyTo50L' : IDL.Null,
    'Under30L' : IDL.Null,
    'FiftyTo80L' : IDL.Null,
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'propertyType' : PropertyType,
    'imageUrls' : IDL.Vec(IDL.Text),
    'bedrooms' : IDL.Nat,
    'tags' : IDL.Vec(LifestyleTag),
    'description' : IDL.Text,
    'postedDaysAgo' : IDL.Nat,
    'furnished' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'areaSqft' : IDL.Nat,
    'isNew' : IDL.Bool,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'locality' : IDL.Text,
    'budgetRange' : BudgetRange,
    'location' : IDL.Text,
    'priceLabel' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'propertyId' : IDL.Opt(IDL.Nat),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const PropertyFilter = IDL.Record({
    'propertyType' : IDL.Opt(PropertyType),
    'tags' : IDL.Vec(LifestyleTag),
    'searchQuery' : IDL.Opt(IDL.Text),
    'locality' : IDL.Opt(IDL.Text),
    'budgetRange' : IDL.Opt(BudgetRange),
  });
  
  return IDL.Service({
    'getFeatured' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getProperties' : IDL.Func(
        [PropertyFilter],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
    'getRecommended' : IDL.Func([IDL.Nat], [IDL.Vec(Property)], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };