/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Property {
    id: bigint;
    title: string;
    propertyType: PropertyType;
    imageUrls: Array<string>;
    bedrooms: bigint;
    tags: Array<LifestyleTag>;
    description: string;
    postedDaysAgo: bigint;
    furnished: string;
    isFeatured: boolean;
    areaSqft: bigint;
    isNew: boolean;
    bathrooms: bigint;
    price: bigint;
    locality: string;
    budgetRange: BudgetRange;
    location: string;
    priceLabel: string;
}
export interface Inquiry {
    id: bigint;
    name: string;
    propertyId?: bigint;
    message: string;
    timestamp: bigint;
    phone: string;
}
export interface PropertyFilter {
    propertyType?: PropertyType;
    tags: Array<LifestyleTag>;
    searchQuery?: string;
    locality?: string;
    budgetRange?: BudgetRange;
}
export enum BudgetRange {
    Above80L = "Above80L",
    ThirtyTo50L = "ThirtyTo50L",
    Under30L = "Under30L",
    FiftyTo80L = "FiftyTo80L"
}
export enum LifestyleTag {
    GreatView = "GreatView",
    LuxuryAmenities = "LuxuryAmenities",
    InvestmentReady = "InvestmentReady",
    NearSchools = "NearSchools",
    ReadyToMove = "ReadyToMove",
    FamilyFriendly = "FamilyFriendly"
}
export enum PropertyType {
    Commercial = "Commercial",
    Plot = "Plot",
    Villa = "Villa",
    Penthouse = "Penthouse",
    Apartment = "Apartment"
}
export interface backendInterface {
    getFeatured(): Promise<Array<Property>>;
    getInquiries(): Promise<Array<Inquiry>>;
    getProperties(filter: PropertyFilter): Promise<Array<Property>>;
    getProperty(id: bigint): Promise<Property | null>;
    getRecommended(limit: bigint): Promise<Array<Property>>;
    submitInquiry(name: string, phone: string, message: string, propertyId: bigint | null): Promise<bigint>;
}
import type { BudgetRange as _BudgetRange, Inquiry as _Inquiry, LifestyleTag as _LifestyleTag, Property as _Property, PropertyFilter as _PropertyFilter, PropertyType as _PropertyType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getFeatured(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeatured();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeatured();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiries();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiries();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperties(arg0: PropertyFilter): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperties(to_candid_PropertyFilter_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperties(to_candid_PropertyFilter_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: bigint): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommended(arg0: bigint): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommended(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommended(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_BudgetRange_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetRange): BudgetRange {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_LifestyleTag_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LifestyleTag): LifestyleTag {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Property_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Property {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Property]): Property | null {
    return value.length === 0 ? null : from_candid_Property_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    propertyId: [] | [bigint];
    message: string;
    timestamp: bigint;
    phone: string;
}): {
    id: bigint;
    name: string;
    propertyId?: bigint;
    message: string;
    timestamp: bigint;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        propertyId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.propertyId)),
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    propertyType: _PropertyType;
    imageUrls: Array<string>;
    bedrooms: bigint;
    tags: Array<_LifestyleTag>;
    description: string;
    postedDaysAgo: bigint;
    furnished: string;
    isFeatured: boolean;
    areaSqft: bigint;
    isNew: boolean;
    bathrooms: bigint;
    price: bigint;
    locality: string;
    budgetRange: _BudgetRange;
    location: string;
    priceLabel: string;
}): {
    id: bigint;
    title: string;
    propertyType: PropertyType;
    imageUrls: Array<string>;
    bedrooms: bigint;
    tags: Array<LifestyleTag>;
    description: string;
    postedDaysAgo: bigint;
    furnished: string;
    isFeatured: boolean;
    areaSqft: bigint;
    isNew: boolean;
    bathrooms: bigint;
    price: bigint;
    locality: string;
    budgetRange: BudgetRange;
    location: string;
    priceLabel: string;
} {
    return {
        id: value.id,
        title: value.title,
        propertyType: from_candid_PropertyType_n4(_uploadFile, _downloadFile, value.propertyType),
        imageUrls: value.imageUrls,
        bedrooms: value.bedrooms,
        tags: from_candid_vec_n6(_uploadFile, _downloadFile, value.tags),
        description: value.description,
        postedDaysAgo: value.postedDaysAgo,
        furnished: value.furnished,
        isFeatured: value.isFeatured,
        areaSqft: value.areaSqft,
        isNew: value.isNew,
        bathrooms: value.bathrooms,
        price: value.price,
        locality: value.locality,
        budgetRange: from_candid_BudgetRange_n9(_uploadFile, _downloadFile, value.budgetRange),
        location: value.location,
        priceLabel: value.priceLabel
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Above80L: null;
} | {
    ThirtyTo50L: null;
} | {
    Under30L: null;
} | {
    FiftyTo80L: null;
}): BudgetRange {
    return "Above80L" in value ? BudgetRange.Above80L : "ThirtyTo50L" in value ? BudgetRange.ThirtyTo50L : "Under30L" in value ? BudgetRange.Under30L : "FiftyTo80L" in value ? BudgetRange.FiftyTo80L : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Commercial: null;
} | {
    Plot: null;
} | {
    Villa: null;
} | {
    Penthouse: null;
} | {
    Apartment: null;
}): PropertyType {
    return "Commercial" in value ? PropertyType.Commercial : "Plot" in value ? PropertyType.Plot : "Villa" in value ? PropertyType.Villa : "Penthouse" in value ? PropertyType.Penthouse : "Apartment" in value ? PropertyType.Apartment : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    GreatView: null;
} | {
    LuxuryAmenities: null;
} | {
    InvestmentReady: null;
} | {
    NearSchools: null;
} | {
    ReadyToMove: null;
} | {
    FamilyFriendly: null;
}): LifestyleTag {
    return "GreatView" in value ? LifestyleTag.GreatView : "LuxuryAmenities" in value ? LifestyleTag.LuxuryAmenities : "InvestmentReady" in value ? LifestyleTag.InvestmentReady : "NearSchools" in value ? LifestyleTag.NearSchools : "ReadyToMove" in value ? LifestyleTag.ReadyToMove : "FamilyFriendly" in value ? LifestyleTag.FamilyFriendly : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Array<Property> {
    return value.map((x)=>from_candid_Property_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LifestyleTag>): Array<LifestyleTag> {
    return value.map((x)=>from_candid_LifestyleTag_n7(_uploadFile, _downloadFile, x));
}
function to_candid_BudgetRange_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetRange): _BudgetRange {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_LifestyleTag_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LifestyleTag): _LifestyleTag {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyFilter_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyFilter): _PropertyFilter {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    propertyType?: PropertyType;
    tags: Array<LifestyleTag>;
    searchQuery?: string;
    locality?: string;
    budgetRange?: BudgetRange;
}): {
    propertyType: [] | [_PropertyType];
    tags: Array<_LifestyleTag>;
    searchQuery: [] | [string];
    locality: [] | [string];
    budgetRange: [] | [_BudgetRange];
} {
    return {
        propertyType: value.propertyType ? candid_some(to_candid_PropertyType_n17(_uploadFile, _downloadFile, value.propertyType)) : candid_none(),
        tags: to_candid_vec_n19(_uploadFile, _downloadFile, value.tags),
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none(),
        locality: value.locality ? candid_some(value.locality) : candid_none(),
        budgetRange: value.budgetRange ? candid_some(to_candid_BudgetRange_n22(_uploadFile, _downloadFile, value.budgetRange)) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    Commercial: null;
} | {
    Plot: null;
} | {
    Villa: null;
} | {
    Penthouse: null;
} | {
    Apartment: null;
} {
    return value == PropertyType.Commercial ? {
        Commercial: null
    } : value == PropertyType.Plot ? {
        Plot: null
    } : value == PropertyType.Villa ? {
        Villa: null
    } : value == PropertyType.Penthouse ? {
        Penthouse: null
    } : value == PropertyType.Apartment ? {
        Apartment: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LifestyleTag): {
    GreatView: null;
} | {
    LuxuryAmenities: null;
} | {
    InvestmentReady: null;
} | {
    NearSchools: null;
} | {
    ReadyToMove: null;
} | {
    FamilyFriendly: null;
} {
    return value == LifestyleTag.GreatView ? {
        GreatView: null
    } : value == LifestyleTag.LuxuryAmenities ? {
        LuxuryAmenities: null
    } : value == LifestyleTag.InvestmentReady ? {
        InvestmentReady: null
    } : value == LifestyleTag.NearSchools ? {
        NearSchools: null
    } : value == LifestyleTag.ReadyToMove ? {
        ReadyToMove: null
    } : value == LifestyleTag.FamilyFriendly ? {
        FamilyFriendly: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetRange): {
    Above80L: null;
} | {
    ThirtyTo50L: null;
} | {
    Under30L: null;
} | {
    FiftyTo80L: null;
} {
    return value == BudgetRange.Above80L ? {
        Above80L: null
    } : value == BudgetRange.ThirtyTo50L ? {
        ThirtyTo50L: null
    } : value == BudgetRange.Under30L ? {
        Under30L: null
    } : value == BudgetRange.FiftyTo80L ? {
        FiftyTo80L: null
    } : value;
}
function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LifestyleTag>): Array<_LifestyleTag> {
    return value.map((x)=>to_candid_LifestyleTag_n20(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
